[build]
    base = "./"
    publish = "./storage/app/static"
    command = "npm run production && php please ssg:generate"

[context.production.environment]
    PHP_VERSION="8.0"
    APP_URL="https://davidalindahl.com"


[[headers]]
  for = "/feed"
  [headers.values]
	Content-Type = "application/rss+xml"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
	Content-Type = "application/xml"

[[headers]]
  for = "css/site.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "js/site.js"
  [headers.values]
    Cache-Control = "max-age=31536000"
