[build]
    base = "./"
    publish = "./storage/app/static"
    command = "npm run production && php please ssg:generate"

[context.production.environment]
    PHP_VERSION="8.0"
    APP_URL="https://davidalindahl.com"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
	Content-Type = "application/xml"
