title: 'Site Settings'
data:
  meta_title: 'David A. Lindahl'
  meta_description: 'Front End/UI Developer | E-commerce Entrepreneur | Outdoor Adventurer | Design Enthusiast | Photographer'
  header_scripts:
    -
      description: 'fathom code'
      code: |
        <!-- Fathom - beautiful, simple website analytics -->
        <script src="https://loon.davidalindahl.com/script.js" site="ALOHVAQX" defer></script>
        <!-- / Fathom -->
